version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=admin
      - MARIADB_DATABASE=laravel
      - MARIADB_PASSWORD=admin
    ports:
      - 3306:3306
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
        - mariadb
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOSTS=mariadb
      - PMA_PORT=3306

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=admin
      - DB_DATABASE=laravel
      - DB_PASSWORD=admin
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
